<<<<<<< HEAD
// Code generated by mockery v1.0.0. DO NOT EDIT.
=======
// Code generated by mockery v2.14.0. DO NOT EDIT.
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19

package mocks

import mock "github.com/stretchr/testify/mock"

<<<<<<< HEAD
// AppCapabilities is an autogenerated mock type for the AppCapabilities type
type AppCapabilities struct {
=======
// ApplicationCapabilities is an autogenerated mock type for the ApplicationCapabilities type
type ApplicationCapabilities struct {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	mock.Mock
}

// ACLs provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) ACLs() bool {
=======
func (_m *ApplicationCapabilities) ACLs() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// CollectionUpgrade provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) CollectionUpgrade() bool {
=======
func (_m *ApplicationCapabilities) CollectionUpgrade() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ForbidDuplicateTXIdInBlock provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) ForbidDuplicateTXIdInBlock() bool {
=======
func (_m *ApplicationCapabilities) ForbidDuplicateTXIdInBlock() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// KeyLevelEndorsement provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) KeyLevelEndorsement() bool {
=======
func (_m *ApplicationCapabilities) KeyLevelEndorsement() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// LifecycleV20 provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) LifecycleV20() bool {
=======
func (_m *ApplicationCapabilities) LifecycleV20() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MetadataLifecycle provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) MetadataLifecycle() bool {
=======
func (_m *ApplicationCapabilities) MetadataLifecycle() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PrivateChannelData provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) PrivateChannelData() bool {
=======
func (_m *ApplicationCapabilities) PrivateChannelData() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// PurgePvtData provides a mock function with given fields:
func (_m *ApplicationCapabilities) PurgePvtData() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// StorePvtDataOfInvalidTx provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) StorePvtDataOfInvalidTx() bool {
=======
func (_m *ApplicationCapabilities) StorePvtDataOfInvalidTx() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Supported provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) Supported() error {
=======
func (_m *ApplicationCapabilities) Supported() error {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// V1_1Validation provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) V1_1Validation() bool {
=======
func (_m *ApplicationCapabilities) V1_1Validation() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// V1_2Validation provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) V1_2Validation() bool {
=======
func (_m *ApplicationCapabilities) V1_2Validation() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// V1_3Validation provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) V1_3Validation() bool {
=======
func (_m *ApplicationCapabilities) V1_3Validation() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// V2_0Validation provides a mock function with given fields:
<<<<<<< HEAD
func (_m *AppCapabilities) V2_0Validation() bool {
=======
func (_m *ApplicationCapabilities) V2_0Validation() bool {
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
<<<<<<< HEAD
=======

type mockConstructorTestingTNewApplicationCapabilities interface {
	mock.TestingT
	Cleanup(func())
}

// NewApplicationCapabilities creates a new instance of ApplicationCapabilities. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApplicationCapabilities(t mockConstructorTestingTNewApplicationCapabilities) *ApplicationCapabilities {
	mock := &ApplicationCapabilities{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
>>>>>>> a5405e2ca41902d62fe0fa9caa102e0d818c2f19
